accounts:
  - name: alice
    coins: ["20000000000proof"]
  - name: bob
    coins: ["100000000000proof"]
validator:
  name: alice
  staked: "100000000proof"
client:
  openapi:
    path: "docs/static/openapi.yml"
  vuex:
    path: "vue/src/store"
faucet:
  name: bob
  coins: ["5000000proof"]
